# Generated by Django 3.2.25 on 2025-06-18 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_rename_hora_publicacion_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('posicion', models.CharField(max_length=10)),
                ('caracteristicas', models.TextField()),
                ('ciudad', models.TextField()),
                ('valor', models.CharField(max_length=10)),
                ('altura', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
