# Generated by Django 3.2.25 on 2025-06-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_jugadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='posicion',
            field=models.CharField(max_length=25),
        ),
    ]
